#pragma once

#define MAX_PLAYERS 2
#define DEFAULT_LIFE 20
#define MAX_NAME_LEN 64
#define DEFAULT_ROUND_TIME 3000000

#define PERSIST_KEY_GAME_STATE 0
#define PERSIST_KEY_SETTINGS_VERSION 1
#define PERSIST_KEY_SETTINGS_DATA 2
