#pragma once

#define STORAGE_PLAYER_ONE_KEY 0x1
#define STORAGE_PLAYER_ONE_NAME_KEY 0x2
#define STORAGE_PLAYER_TWO_KEY 0x3
#define STORAGE_PLAYER_TWO_NAME_KEY 0x4

#define STORAGE_ROUND_TIME_KEY 0x5
#define STORAGE_LAST_RUN_KEY 0x6
